# Generated by Django 5.0.4 on 2024-04-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelformapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='cpassword',
            new_name='conf_password',
        ),
    ]
